#!/usr/bin/env python

import sys
import os
from os.path import curdir, realpath

environ = os.environ
if 'PYTHONPATH' in environ:
    environ['PYTHONPATH'] = realpath(curdir) + ":" + environ['PYTHONPATH']
else:
    environ['PYTHONPATH'] = realpath(curdir) 
os.execvpe(sys.argv[1], sys.argv[1:], environ)
